ALTER TABLE TV_PROGRAM
ADD CONSTRAINT TV_PROGRAM_PK PRIMARY KEY (ID);

ALTER TABLE TV_CONTENT
ADD CONSTRAINT TV_PROGRAM_PK_ASSET_ID PRIMARY KEY( ASSET_ID);

ALTER TABLE TV_CONTENT
ADD ASSET_ID NUMBER(20);

ALTER TABLE TV_CONTENT
RENAME TO TV_CONTENT_INFO;

ALTER TABLE TV_CONTENT
RENAME COLUMN ID TO CONTENT_ID;
--POSTER_TYPES
CREATE TABLE TV_CONTENT("CONTENT_ID" NUMBER(20,0), "ASSET_ID" NUMBER(20,0), "NAME_MON" VARCHAR2(150 BYTE), "NAME_ENG" VARCHAR2(150 BYTE), "TYPE" NUMBER(1,0) DEFAULT 1, "CREATED_DATE" DATE DEFAULT SYSDATE, "CREATED_BY" VARCHAR2(50 BYTE), "UPDATED_DATE" DATE, "UPDATED_BY" VARCHAR2(50 BYTE), "DELETED" VARCHAR2(1 BYTE) DEFAULT 'N', "DELETED_DATE" DATE, "DELETED_BY" VARCHAR2(50 BYTE), "IS_PUBLISHED" NUMBER(1,0) DEFAULT 1, "PRICE" NUMBER(20,0) DEFAULT 0, "CONTENT_DESCR" VARCHAR2(2000 BYTE), "IMAGE_WEB" VARCHAR2(500 BYTE), "IMAGE_TRAILER" VARCHAR2(500 BYTE), "IMAGE_POSTER" VARCHAR2(500 BYTE), "DIRECTOR" VARCHAR2(200 BYTE), "YEAR" NUMBER, "DURATION_TIME" NUMBER, "SENT_WEB" VARCHAR2(20 BYTE) DEFAULT 0, "TRAILER" VARCHAR2(20 BYTE), "ISSERIALCONTENT" VARCHAR2(20 BYTE) DEFAULT 'N', "AR_PRICE" NUMBER DEFAULT 0, "NIBBLE1" NUMBER DEFAULT 0, "NIBBLE2" NUMBER DEFAULT 0, "PUSHVOD_CATEGORY" NUMBER DEFAULT 0, "IS_FREE" NUMBER DEFAULT 0, "IS_BOX" VARCHAR2(5 BYTE) DEFAULT 'N', "IS_MGL" VARCHAR2(5 BYTE) DEFAULT 'N');
CREATE TABLE TV_POSTER_TYPES ("TYPE" NUMBER(20,0), "NAME" VARCHAR2(20), "WIDTH" VARCHAR2(20), "HEIGHT" VARCHAR2(20), "MAX_SIZE" VARCHAR2(20));
CREATE TABLE TV_GENRE_LIST ("GENRE_CODE" NUMBER(20,0), "GENRE_NAME" VARCHAR2(20));
CREATE TABLE TV_LIST_OF_GENRES("ID" NUMBER, "GENRES_NAME" VARCHAR2(200), "NAME_MON" VARCHAR2(200 BYTE), "CREATE_DATE" DATE DEFAULT SYSDATE, "IS_ACTIVE" VARCHAR2(20 BYTE) DEFAULT 'Y');
CREATE TABLE TV_CONTENT_GENRES(	"ID" NUMBER, "CONTENT_ID" NUMBER, "GENRES_ID" NUMBER);

ALTER TABLE TV_POSTER_TYPES
DELETE FROM TV_GENRE_LIST;
ALTER TABLE TV_GENRE_LIST MODIFY GENRE_CODE NUMBER(20,0);
    INSERT INTO TV_GENRE_LIST VALUES ('1', 'HORROR');
    INSERT INTO TV_GENRE_LIST VALUES ('2', 'COMEDY');
    INSERT INTO TV_GENRE_LIST VALUES ('3', 'THRILLER');
    INSERT INTO TV_GENRE_LIST VALUES ('4', 'ADVENTURE');
SELECT * FROM tv_genre_list;
CREATE TABLE TV_CONTENT_GENRE ("CONTENT_ID" NUMBER(20,0), "GENRE_CODE" VARCHAR2(10));
SELECT * FROM TV_POSTER_TYPES;
--TV_CONTENT
--TV_PROGRAM
--TV
SELECT * FROM TV_CONTENT_INFO;
CREATE OR REPLACE PACKAGE BODY TV_CONTENT_MANIPULATE AS 
  -- Procedure to add TV content
  PROCEDURE TV_CONTENT_ADD(PARAM1 IN VARCHAR2) IS
  BEGIN
    -- Implementation of TV_CONTENT_ADD
    -- Your code here
    DBMS_OUTPUT.PUT_LINE('TV_CONTENT_ADD procedure executed with PARAM1: ' || PARAM1);
  END TV_CONTENT_ADD;
  -- Procedure to edit TV content
  PROCEDURE TV_CONTENT_EDIT(PARAM1 IN VARCHAR2) IS
  BEGIN
    -- Implementation of TV_CONTENT_EDIT
    -- Your code here
    DBMS_OUTPUT.PUT_LINE('TV_CONTENT_EDIT procedure executed with PARAM1: ' || PARAM1);
  END TV_CONTENT_EDIT;
  -- Procedure to add a poster to TV content
  PROCEDURE TV_CONTENT_ADD_POSTER(PARAM1 IN VARCHAR2) IS
  BEGIN
    -- Implementation of TV_CONTENT_ADD_POSTER
    -- Your code here
    DBMS_OUTPUT.PUT_LINE('TV_CONTENT_ADD_POSTER procedure executed with PARAM1: ' || PARAM1);
  END TV_CONTENT_ADD_POSTER;

  -- Procedure to search for TV content
  PROCEDURE TV_CONTENT_SEARCH_CONTENT(PARAM1 IN VARCHAR2) IS
  BEGIN
    -- Implementation of TV_CONTENT_SEARCH_CONTENT
    -- Your code here
    DBMS_OUTPUT.PUT_LINE('TV_CONTENT_SEARCH_CONTENT procedure executed with PARAM1: ' || PARAM1);
  END TV_CONTENT_SEARCH_CONTENT;

END TV_CONTENT_MANIPULATE;
/