--------------------------------------------------------
--  File created - Tuesday-September-05-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LIST_OF_GENRES
--------------------------------------------------------

  CREATE TABLE "UNI_DISH"."LIST_OF_GENRES" 
   (	"ID" NUMBER, 
	"GENRES_NAME" VARCHAR2(200), 
	"NAME_MON" VARCHAR2(200 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"IS_ACTIVE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'Y'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWHDATA" ;
--------------------------------------------------------
--  DDL for Index LIST_OF_GENRES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNI_DISH"."LIST_OF_GENRES_PK" ON "UNI_DISH"."LIST_OF_GENRES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWHDATA" ;
--------------------------------------------------------
--  DDL for Trigger TR_GENRES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "UNI_DISH"."TR_GENRES" 
BEFORE INSERT ON LIST_OF_GENRES FOR EACH ROW
BEGIN
  SELECT UNI_DISH.SEQ_ACTOR_LIST.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


/
ALTER TRIGGER "UNI_DISH"."TR_GENRES" ENABLE;
--------------------------------------------------------
--  Constraints for Table LIST_OF_GENRES
--------------------------------------------------------

  ALTER TABLE "UNI_DISH"."LIST_OF_GENRES" ADD CONSTRAINT "LIST_OF_GENRES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWHDATA"  ENABLE;
  ALTER TABLE "UNI_DISH"."LIST_OF_GENRES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."LIST_OF_GENRES" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."LIST_OF_GENRES" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
