--------------------------------------------------------
--  DDL for Table TV_CONTENT
--------------------------------------------------------

  CREATE TABLE "UNI_DISH"."TV_CONTENT" 
   (	"ID" NUMBER(20,0), 
	"NAME_MON" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME_ENG" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"DELETED_DATE" DATE, 
	"DELETED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_PUBLISHED" NUMBER(1,0) DEFAULT 1, 
	"PRICE" NUMBER(20,0) DEFAULT 0, 
	"CONTENT_DESCR" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"IMAGE_WEB" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"IMAGE_TRAILER" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"IMAGE_POSTER" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"DIRECTOR" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR" NUMBER, 
	"DURATION_TIME" NUMBER, 
	"SENT_WEB" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 0, 
	"TRAILER" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ISSERIALCONTENT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"AR_PRICE" NUMBER DEFAULT 0, 
	"NIBBLE1" NUMBER DEFAULT 0, 
	"NIBBLE2" NUMBER DEFAULT 0, 
	"PUSHVOD_CATEGORY" NUMBER DEFAULT 0, 
	"IS_FREE" NUMBER DEFAULT 0, 
	"IS_BOX" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"IS_MGL" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWHDATA" ;

   COMMENT ON COLUMN "UNI_DISH"."TV_CONTENT"."IS_BOX" IS 'N is nobox, Y is box';
   COMMENT ON COLUMN "UNI_DISH"."TV_CONTENT"."IS_MGL" IS 'N is no mongolian content, Y is mongolian content';
  GRANT UPDATE ON "UNI_DISH"."TV_CONTENT" TO "IT_TRAINING";
  GRANT INSERT ON "UNI_DISH"."TV_CONTENT" TO "IT_TRAINING";
  GRANT DELETE ON "UNI_DISH"."TV_CONTENT" TO "IT_TRAINING";
  GRANT SELECT ON "UNI_DISH"."TV_CONTENT" TO "IT_TRAINING";
  GRANT SELECT ON "UNI_DISH"."TV_CONTENT" TO "DWHCLIENT";
