--------------------------------------------------------
--  Constraints for Table TV_CONTENT
--------------------------------------------------------

  ALTER TABLE "UNI_DISH"."TV_CONTENT" ADD CONSTRAINT "TV_CONTENT_PK" PRIMARY KEY ("ID")
  USING INDEX "UNI_DISH"."TV_CONTENT_PK"  ENABLE;
  ALTER TABLE "UNI_DISH"."TV_CONTENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."TV_CONTENT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."TV_CONTENT" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."TV_CONTENT" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."TV_CONTENT" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."TV_CONTENT" MODIFY ("IS_PUBLISHED" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."TV_CONTENT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."TV_CONTENT" MODIFY ("ISSERIALCONTENT" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."TV_CONTENT" MODIFY ("AR_PRICE" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."TV_CONTENT" MODIFY ("IS_BOX" NOT NULL ENABLE);
  ALTER TABLE "UNI_DISH"."TV_CONTENT" MODIFY ("IS_MGL" NOT NULL ENABLE);
