--------------------------------------------------------
--  DDL for Index TV_CONTENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNI_DISH"."TV_CONTENT_PK" ON "UNI_DISH"."TV_CONTENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWHDATA" ;
